name:                powser
version:             0.1.1
github:              "Sophia-Gold/PowerSerious"
license:             BSD3
author:              "Doug McIlroy"
maintainer:          "sophiagoldnyc@gmail.com"
copyright:           "2007 Doug McIlroy"

extra-source-files:
- README.md

description:         Basic operations on power series and polynomials represented by lists

dependencies:
- base >= 4.7 && < 5
- comonad
- split

library:
  source-dirs: src

executables:
  powser:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - powser
